# Generated by Django 4.1 on 2022-10-13 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_avatar_delete_imagenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='usern',
        ),
    ]
