# Generated by Django 4.1 on 2022-10-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_posteo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteo',
            old_name='tituo',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='posteo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
