# Generated by Django 4.1 on 2022-10-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_alter_avatar_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagenes',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
