# Generated by Django 4.1 on 2022-10-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_imagenes_avatar_user_posteo_user_alter_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='avatarp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='posteo',
            name='usuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
