# Generated by Django 4.1 on 2022-10-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_posteo_avatarp_posteo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='avatarp',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='usuario',
        ),
    ]
