# Generated by Django 4.1 on 2022-10-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='post_id',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
