# Generated by Django 4.1 on 2022-10-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0016_mensajes_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
