# Generated by Django 4.1 on 2022-10-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0017_alter_mensajes_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
